### ISSUE TITLE
New version 4.2.x

### ISSUE THREAD

**Issue by rysson** [hbiyik/script.module.lxml#1]
Hi, awesome work!

Could I ask you to update this module to the newest version of lxml?

**Comment by hbiyik** [comment]
@rysson thanks, but i am too lazy to upgrade and there are bunch of platforms, is the upgrade really necessary?

**Comment by hbiyik** [comment]
btw for linux https://pypi.org/project/lxml/#files pypi packages will works, for windows needs to be recompiled from scratch
